[package]
name = "qfdrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.2"
rand_distr = "0.5.0-alpha.3"
rayon = "1.10.0"
rustms = { git = "https://github.com/theGreatHerrLebert/rustims.git" }
itertools = "0.12.1"
serde = { version = "1.0.202", features = ["derive"] }
bincode = "2.0.0-rc.3"
serde_json = "1.0.117"
ndarray = "0.15.6"
ndarray-stats = "0.6.0"