[package]
name = "sagepy-connector"
version = "0.2.27"
edition = "2021"

[lib]
name = "sagepy_connector"
crate-type = ["cdylib"]

[dependencies]
# sage-core = {path = "../../sage/crates/sage" }
sage-core = { git = "https://github.com/theGreatHerrLebert/sage.git" }
qfdrust = { path  = "../qfdrust" }
unimod = { path = "../unimod" }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
numpy = "0.21.0"
rayon = "1.10.0"

regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
bincode = "1.3.3"
log = "0.4.21"
itertools = "0.13.0"
serde_json = "1.0.117"
